openapi: 3.0.3
info:
  title: Auto booking swagger - OpenAPI 3.0
  description: |-
    Auto booking swagger
  version: 1.0.11
servers:
  - url: https://localhost:8080
paths:
  /book/{carId}:
    post:
      tags:
        - booking
      summary: Book auto
      description: Book auto by id
      parameters:
        - name: carId
          in: path
          description: ID of car
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: Time interval
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /cost/{carId}:
    get:
      tags:
        - cost
      summary: Rental cost auto
      description: Rental cost auto for period
      parameters:
        - name: carId
          in: path
          description: ID of car
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: Time interval
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CosteResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /availability/{carId}:
    get:
      tags:
        - availability
      summary: Availability auto
      description: Availability auto for period
      parameters:
        - name: carId
          in: path
          description: ID of car
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: Time interval
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interval'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /report:
    get:
      tags:
        - report
      summary: Report on the average vehicle load for the month, for each vehicle and the total for all cars
      description: Report on the average vehicle load for the month, for each vehicle and the total for all cars
      parameters:
        - name: month
          in: query
          description: Number of month
          required: true
          schema:
            type: integer
            format: int
        - name: year
          in: query
          description: Number of year
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Interval:
      type: object
      properties:
        start_date:
          type: string
          example: "2023-11-28 15:04:06"
        end_date:
          type: string
          example: "2023-12-15 15:04:11"
    BookingResponse:
      type: object
      properties:
        status:
          type: string
          example: "Booking created"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error string"
    CosteResponse:
      type: object
      properties:
        cost:
          type: integer
          example: 22222
    AvailabilityResponse:
      type: object
      properties:
        available:
          type: boolean
          example: true
    ReportResponse:
      type: object
      properties:
        average_usage:
          type: float
          example: 22222.44
    